export interface Account {
    id?: any,
    accountName?: String,
    holder?: String,
    holderDocument?: String,
    limitValue?: Number,
    modality?: String,
    bank?: String,
    type?: String,
    agency?: String,
    agencyDv?: String,
    account?: String,
    accountDv?: String,
    balance?: Number,
    active?: Boolean,
}